name: CI

on:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.0

  nox-sessions-matrix-split:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nox nox-poetry
      - id: set-matrix
        run: |
          echo "::set-output name=matrix::$( nox -l | grep '\*' | grep '\->' | awk '{print $2}' | jq --raw-input | jq --slurp -c '.[] | {session: .}' | jq --slurp -c '. | {include: .}' )"

  nox:
    needs: nox-sessions-matrix-split
    strategy:
      matrix: ${{ fromJson(needs.nox-sessions-matrix-split.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry nox nox-poetry
      - name: Running nox
        run: |
          nox --session "${{ matrix.session }}" --force-color
      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          name: "${{ matrix.session }}"
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} # not required for public repos

      - name: Upload coverage report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: "coverage-report-${{ matrix.session }}"
          path: build/coverage
